### PR TITLE
Update Spacings

### PR DESCRIPTION
**Pull request by MelodicAlbuild**
Your Image and Text are really close, my brain hates it so I fixed it for you :)

### CODE REVIEW

**Comment by MelodicAlbuild** [comment]
The lowercase in your "Bio" doesn't work with the rest of the website

**Comment by MelodicAlbuild** [comment]
Might as well update your Meta Tags while I'm at it

**Comment by acollierr17** [comment]
Changes look good to me! And yeah, if you want to go ahead and update the meta tags, I'm for it! I'll merge the changes then.

**Comment by MelodicAlbuild** [comment]
Go for it, all my commits are done

**Review by acollierr17 — APPROVED** [review]

**Pull request merged**
